Products:
  class: Pantono\Products\Products
Categories:
  class: Pantono\Products\Categories
ProductApproval:
  class: Pantono\Products\ProductApproval
ProductHistory:
  class: Pantono\Products\ProductHistory
Discounts:
  class: Pantono\Products\Discounts
