Products:
  class: Pantono\Products\Products
Categories:
  class: Pantono\Products\Categories
ProductApproval:
  class: Pantono\Products\ProductApproval
ProductHistory:
  class: Pantono\Products\ProductHistory
ProductDiscounts:
  class: Pantono\Products\ProductDiscounts
ProductReviews:
  class: Pantono\Products\ProductReviews
ProductFavourites:
  class: Pantono\Products\ProductFavourites
ProductStats:
  class: Pantono\Products\ProductStats
